routes/web.php
<?php

use App\Models\ListRole;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require __DIR__.'/auth.php';

Route::get('', 'HomeController@index');
Route::get('/', 'HomeController@index');
Route::resource('/home', 'Front\HomeController');

//register
Route::get('/pendaftaran', 'Front\RegisterController@index');
Route::post('/pendaftaran/store', 'Front\RegisterController@store');
Route::resource('/cek-pengaduan', 'Front\CekPengaduanController');
Route::post('/search-pengaduan', 'Front\CekPengaduanController@searchPengaduan')->name('searchpengaduan');


Route::namespace('Admin')->name('admin.')->prefix('admin')->middleware('auth', 'role:admin')->group(function() {
    Route::namespace('Master')->name('master.')->prefix('master')->group(function() {
        Route::get('', 'HomeController@index');
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
        Route::resource('user', 'UserController');
        Route::get('data/user', 'UserController@data')->name('user.data');
        Route::resource('kategori-pengaduan', 'KategoriPengaduanController');
        Route::get('data/kategori-pengaduan', 'KategoriPengaduanController@data')->name('kategori-pengaduan.data');
        Route::resource('status-tindaklanjut', 'StatusTindaklanjutController');
        Route::get('data/status-tindaklanjut', 'StatusTindaklanjutController@data')->name('status-tindaklanjut.data');
        Route::resource('departemen', 'DepartemenController');
        Route::get('data/departemen', 'DepartemenController@data')->name('departemen.data');
        Route::resource('pengaduan', 'PengaduanController');
        Route::get('data/pengaduan', 'PengaduanController@data')->name('pengaduan.data');

        Route::resource('verifikasipengaduan', 'VerifikasiPengaduanController');
        Route::get('data/verifikasipengaduan', 'VerifikasiPengaduanController@data')->name('verifikasipengaduan.data');
    });
});

//pelapor
Route::namespace('Pelapor')->name('pelapor.')->prefix('pelapor')->middleware('auth', 'role:pelapor')->group(function() {
    Route::get('', 'HomeController@index');
    Route::resource('pengaduan', 'PengaduanController');
    Route::get('data/pengaduan', 'PengaduanController@data')->name('pengaduan.data');
    Route::get('pengaduan/getuserlogin', 'PengaduanController@getUserLogin');
    Route::get('/pengaduan/viewdetail/{id}', 'PengaduanController@viewDetail')->name('pengaduan.viewdetail'); 

    Route::resource('tindaklanjutpengaduan', 'TindakLanjutController');

    Route::resource('pengaduanditolak', 'PengaduanDitolakController');
    Route::resource('profile', 'ProfileController');
    Route::get('changepassword', 'ProfileController@viewChangePassword')->name('changepassword');
    Route::put('profile/changepassword/{id}', 'ProfileController@changePassword');
});

//departemen
Route::namespace('Departemen')->name('departemen.')->prefix('departemen')->middleware('auth', 'role:departemen')->group(function() {
    Route::get('', 'HomeController@index');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
    Route::resource('pengaduan', 'PengaduanController');
    Route::get('data/pengaduan', 'PengaduanController@data')->name('pengaduan.data');
    Route::get('/pengaduan/viewdetail/{id}', 'PengaduanController@viewDetail')->name('pengaduan.viewdetail'); 
    Route::post('/pengaduan/viewdetail/storetindaklanjut', 'PengaduanController@storetindaklanjut')->name('pengaduan.viewdetail.storetindaklanjut');
    Route::get('/pengaduan/viewdetail/edittindaklanjut/{id}', 'PengaduanController@edittindaklanjut')->name('pengaduan.viewdetail.edittindaklanjut');
    Route::put('/pengaduan/viewdetail/updatetindaklanjut/{id}', 'PengaduanController@updatetindaklanjut')->name('pengaduan.viewdetail.updatetindaklanjut');
    Route::put('/pengaduan/viewdetail/tutuppengaduan/{id}', 'PengaduanController@tutuppengaduan')->name('pengaduan.viewdetail.tutuppengaduan');
    Route::put('/pengaduan/viewdetail/bukapengaduan/{id}', 'PengaduanController@bukapengaduan')->name('pengaduan.viewdetail.bukapengaduan');
    Route::delete('/pengaduan/viewdetail/destroytindaklanjut/{id}', 'PengaduanController@destroytindaklanjut')->name('pengaduan.viewdetail.destroytindaklanjut');
});

//pengawas
Route::namespace('Pengawas')->name('pengawas.')->prefix('pengawas')->middleware('auth', 'role:pengawas')->group(function() {
    Route::get('', 'HomeController@index');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
    Route::resource('pengaduan', 'PengaduanController');
    Route::get('data/pengaduan', 'PengaduanController@data')->name('pengaduan.data');
    Route::get('/pengaduan/viewdetail/{id}', 'PengaduanController@viewDetail')->name('pengaduan.viewdetail'); 
    Route::post('/pengaduan/viewdetail/storetindaklanjut', 'PengaduanController@storetindaklanjut')->name('pengaduan.viewdetail.storetindaklanjut');
    Route::get('/pengaduan/viewdetail/edittindaklanjut/{id}', 'PengaduanController@edittindaklanjut')->name('pengaduan.viewdetail.edittindaklanjut');
    Route::put('/pengaduan/viewdetail/updatetindaklanjut/{id}', 'PengaduanController@updatetindaklanjut')->name('pengaduan.viewdetail.updatetindaklanjut');
    Route::put('/pengaduan/viewdetail/tutuppengaduan/{id}', 'PengaduanController@tutuppengaduan')->name('pengaduan.viewdetail.tutuppengaduan');
    Route::put('/pengaduan/viewdetail/bukapengaduan/{id}', 'PengaduanController@bukapengaduan')->name('pengaduan.viewdetail.bukapengaduan');
    Route::delete('/pengaduan/viewdetail/destroytindaklanjut/{id}', 'PengaduanController@destroytindaklanjut')->name('pengaduan.viewdetail.destroytindaklanjut');
});

resources/views/layout/guest.blade.php
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Sistem Informasi Manajemen Hasil SWAB Test Rumah Sakit Bhayangkara Denpasar">
    <meta name="keywords" content="swab test, rumah sakit, bhayangkara, denpasar, trijata">
    <meta name="author" content="PT. ARCOM Bali">
    <title>@yield('title') | RS Trijata</title>
    <link rel="apple-touch-icon" href="{{ asset('images/logo-rs.png') }}">
    <link rel="shortcut icon" type="image/x-icon" href="{{ asset('images/logo-rs.png') }}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600" rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('app-assets/vendors/css/vendors.min.css')}}">
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/bootstrap.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/bootstrap-extended.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/colors.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/components.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/themes/dark-layout.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/themes/bordered-layout.css')}}">

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/core/menu/menu-types/vertical-menu.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/pages/page-misc.css')}}">
    <!-- END: Page CSS-->

    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/style.css')}}">
    <!-- END: Custom CSS-->

    {{-- BEGIN: Content CSS --}}
    @yield('css')
    {{-- END: Content CSS --}}

</head>
<!-- END: Head-->

<!-- BEGIN: Body-->

<body class="vertical-layout vertical-menu-modern blank-page navbar-floating footer-static  " data-open="click" data-menu="vertical-menu-modern" data-col="blank-page">
    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            <div class="content-header row">
            </div>
            <div class="content-body">
                @yield('content')
            </div>
        </div>
    </div>
    <!-- END: Content-->


    <!-- BEGIN: Vendor JS-->
    <script src="{{ asset('app-assets/vendors/js/vendors.min.js')}}"></script>
    <!-- BEGIN Vendor JS-->

    <!-- BEGIN: Page Vendor JS-->
    <!-- END: Page Vendor JS-->

    <!-- BEGIN: Theme JS-->
    <script src="{{ asset('app-assets/js/core/app-menu.js')}}"></script>
    <script src="{{ asset('app-assets/js/core/app.js')}}"></script>
    <!-- END: Theme JS-->

    <!-- BEGIN: Page JS-->
    <!-- END: Page JS-->

    <script>
        $(window).on('load', function() {
            if (feather) {
                feather.replace({
                    width: 14,
                    height: 14
                });
            }
        })
    </script>
    {{-- BEGIN: Content CSS --}}
    @yield('js')
    {{-- END: Content CSS --}}
</body>
<!-- END: Body-->

</html>

resources/views/layout/home.blade.php
@extends('layout.layout')

@section('title', 'Dashboard')

@section('css')
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/dataTables.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/buttons.bootstrap4.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/pickers/flatpickr/flatpickr.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/forms/pickers/form-flat-pickr.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/extensions/sweetalert2.min.css') }}">
@endsection

@section('content')
	{{-- BEGIN: Datatable Button --}}
	<section>
        {{-- BEGIN: Table --}}
        <x-datatable-button title="Data Pengumuman" id="tambah" buttonTitle='<i data-feather="plus"></i> Tambah'>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th data-priority="1">Judul</th>
						<th>Conference</th>
						<th>Tanggal</th>
                        <th>Jumlah Dilihat</th>
                        <th data-priority="2"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Contoh Pengumuman</td>
						<td>Contoh Conference</td>
						<td>20 Desember 2021</td>
						<td>15x</td>
                        <td class="text-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-warning ubah"><i data-feather="edit-2"></i></button>
                                <button type="button" class="btn btn-danger deleteBtn" onclick="hapus(1)"><i data-feather="trash"></i></button>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>

            <form id="delete-form" action="#" method="POST" class="d-none">
                @csrf
                @method('DELETE')
            </form>
        </x-datatable-button>
        {{-- END: Table --}}
		
		{{-- BEGIN: Modal --}}
		<x-modal title="" type="normal" class="" id="modal">
			<div class="modal-body">
				<x-form-group title="Judul">
					<input type="text" class="form-control" id="judul" placeholder="Judul Pengumuman" required/>
                </x-form-group>
                
                <x-form-group title="Conference">
					<select class="form-control" id="conference" required>
						<option value="" hidden>-- Pilih Conference --</option>
						<option value="1">Contoh Conference</option>
					</select>
                </x-form-group>
                
                <x-form-group title="Tanggal">
					<input type="text" class="form-control flatpickr-basic" placeholder="Tanggal Pengumuman" id="tanggal" required/>
                </x-form-group>
                
                <x-form-group title="Deskripsi">
                    <textarea class="form-control" id="deskripsi" rows="5" placeholder="Deskripsi Pengumuman" required></textarea>
                </x-form-group>

                <div id="tambah-gambar">
					<x-form-group title="Gambar">
						<input type="file" class="form-control-file" required/>
					</x-form-group>
				</div>
				<div id="ubah-gambar">
					Ini Contoh Gambar []
					<x-form-group title="Ubah Gambar">
						<input type="file" class="form-control-file" required/>
					</x-form-group>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary mr-1" id="button-tambah"><i data-feather="check"></i> Simpan</button>
				<button type="button" class="btn btn-primary mr-1" id="button-ubah"><i data-feather="edit-2"></i> Ubah</button>
				<button type="reset" class="btn btn-outline-danger" id="button-batal" data-dismiss="modal"><i data-feather="x"></i> Batal</button>
				<button type="button" class="btn btn-outline-danger" id="button-hapus"><i data-feather="trash"></i> Hapus</button>
			</div>
		</x-modal>
		{{-- END: Modal --}}
	</section>
	{{-- END: Datatable Button --}}
@endsection

@section('js')
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
	<script src="{{ asset('app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js') }}"></script>
	<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.buttons.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/jszip.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/pdfmake.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/buttons.html5.min.js') }}"></script>
	<script src="{{ asset('app-assets/vendors/js/tables/datatable/buttons.print.min.js') }}"></script>
	<script src="{{ asset('app-assets/vendors/js/pickers/flatpickr/flatpickr.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/extensions/sweetalert2.all.min.js') }}"></script>
    <script src="{{ asset('app-assets/js/scripts/extensions/ext-component-sweet-alerts.js') }}"></script>

	{{-- Datatable --}}
	<script>
		var link = null;
	</script>
	<script src="{{ asset('js/component/datatable-button.js') }}"></script>
	<script>
		// Date Picker
		$('.flatpickr-basic').flatpickr();

        // SweetAlert
        function hapus(id) {
            
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                customClass: {
                    confirmButton: 'btn btn-primary',
                    cancelButton: 'btn btn-outline-danger ml-1'
                },
                buttonsStyling: false
            }).then(function (result) {
                if (result.value) {
                    Swal.fire({
                        icon: 'success',
                        title: 'Deleted!',
                        text: 'Your file has been deleted.',
                        customClass: {
                            confirmButton: 'btn btn-success'
                        },
                        showConfirmButton: false
                    });

                    $('#delete-form').attr('action', '{{ url("hapus") }}/' + id);
                    $('#delete-form').submit();
                } else if (result.dismiss === Swal.DismissReason.cancel) {
                    Swal.fire({
                        title: 'Cancelled',
                        text: 'Your imaginary file is safe :)',
                        icon: 'error',
                        customClass: {
                            confirmButton: 'btn btn-success'
                        }
                    });
                }
            });
        }

		// Modal
		$(document).ready(function() {
			$('#tambah').on('click', function() {
				$('.modal-title').text('Tambah Keynote Speaker');

				$('#tambah-gambar').attr('hidden', false);
				$('#ubah-gambar').attr('hidden', true);

				$('#button-tambah').attr('hidden', false);
				$('#button-batal').attr('hidden', false);
				$('#button-ubah').attr('hidden', true);
				$('#button-hapus').attr('hidden', true);
				
				$('#modal').modal('show');
			});

			$('.ubah').on('click', function() {
				$('.modal-title').text('Ubah Pengumuman');

				$('#tambah-gambar').attr('hidden', true);
				$('#ubah-gambar').attr('hidden', false);

				$('#judul').val('Contoh Judul');
				$('#conference').val(1);
				$('#tanggal').val('2021-02-27');
				$('#deskripsi').val('Contoh Deskripsi');

				$('#button-tambah').attr('hidden', true);
				$('#button-batal').attr('hidden', true);
				$('#button-ubah').attr('hidden', false);
				$('#button-hapus').attr('hidden', false);


				$('#modal').modal('show');
			});

			$('#modal').on('hidden.bs.modal', function (e) {
				$('#judul').val('');
				$('#ubah-gambar input').val('');
				$('#tambah-gambar input').val('');
				$('#conference').val('');
				$('#tanggal').val('');
				$('#deskripsi').val('');
			});
		});
	</script>
@endsection

resources/views/layout/menu.blade.php
@if (request()->is('admin') || request()->is('admin/*'))
    <li class="navigation-header"><span>Analytics</span><i data-feather="more-horizontal"></i></li>
    <li class="nav-item {{ (request()->routeIs('admin.master.dashboard.*')) ? 'active' : '' }}"><a class="d-flex align-items-center" href="{{route('admin.master.dashboard.index')}}"><i data-feather="home"></i><span class="menu-title text-truncate">Dashboard</span></a></li>
    
    {{-- Data Master--}}
    <li class="navigation-header"><span>Master</span><i data-feather="more-horizontal"></i></li>
    <li class="nav-item {{ (request()->routeIs('admin.master.user.*')) ? 'active' : '' }}"><a class="d-flex align-items-center" href="{{ route('admin.master.user.index') }}"><i data-feather="user"></i><span class="menu-title text-truncate">User</span></a></li>
    <li class="nav-item {{ (request()->routeIs('admin.master.kategori-pengaduan.*')) ? 'active' : '' }}"><a class="d-flex align-items-center" href="{{ route('admin.master.kategori-pengaduan.index') }}"><i data-feather="cloud"></i><span class="menu-title text-truncate">Kategori Pengaduan</span></a></li>
    <li class="nav-item {{ (request()->routeIs('admin.master.status-tindaklanjut.*')) ? 'active' : '' }}"><a class="d-flex align-items-center" href="{{ route('admin.master.status-tindaklanjut.index') }}"><i data-feather="activity"></i><span class="menu-title text-truncate">Status Tindak Lanjut</span></a></li>
    <li class="nav-item {{ (request()->routeIs('admin.master.departemen.*')) ? 'active' : '' }}"><a class="d-flex align-items-center" href="{{ route('admin.master.departemen.index') }}"><i data-feather="box"></i><span class="menu-title text-truncate">Departemen</span></a></li>
    
    <li class="navigation-header"><span>Manajemen Pengaduan</span><i data-feather="more-horizontal"></i></li>
    <li class="nav-item {{ (request()->routeIs('admin.master.pengaduan.*')) ? 'active' : '' }}"><a class="d-flex align-items-center" href="{{ route('admin.master.pengaduan.index') }}"><i data-feather="package"></i><span class="menu-title text-truncate">Pengaduan</span></a></li>
    <li class="nav-item {{ (request()->routeIs('admin.master.verifikasipengaduan.*')) ? 'active' : '' }}"><a class="d-flex align-items-center" href="{{ route('admin.master.verifikasipengaduan.index') }}"><i data-feather="check-circle"></i><span class="menu-title text-truncate">Verifikasi Pengaduan</span> <span class="badge mr-1 ml-auto badge-light-danger badge-pill">{{$total_pengaduan_bv ?? ''}}</span></a></li>

@elseif (request()->is('pelapor*'))
    <li class="navigation-header"><span>Manajemen Pengaduan</span><i data-feather="more-horizontal"></i></li>
    <li class="nav-item {{ (request()->routeIs('pelapor.pengaduan.*')) ? 'active' : '' }}"><a class="d-flex align-items-center" href="{{ route('pelapor.pengaduan.index') }}"><i data-feather="package"></i><span class="menu-title text-truncate">Pengaduan</span></a></li>
    <li class="navigation-header"><span>Setting</span><i data-feather="more-horizontal"></i></li>
    <li class="nav-item {{ (request()->routeIs('pelapor.profile.*')) ? 'active' : '' }}"><a class="d-flex align-items-center" href="{{ route('pelapor.profile.index') }}"><i data-feather="user"></i><span class="menu-title text-truncate">Profil</span></a></li>
    <li class="nav-item {{ (request()->routeIs('pelapor.changepassword')) ? 'active' : '' }}"><a class="d-flex align-items-center" href="{{ route('pelapor.changepassword') }}"><i data-feather="key"></i><span class="menu-title text-truncate">Ganti Password</span></a></li>
    
    
@elseif (request()->is('departemen*'))
    <li class="navigation-header"><span>Analytics</span><i data-feather="more-horizontal"></i></li>
    <li class="nav-item {{ (request()->routeIs('departemen.dashboard.*')) ? 'active' : '' }}"><a class="d-flex align-items-center" href="{{route('departemen.dashboard.index')}}"><i data-feather="home"></i><span class="menu-title text-truncate">Dashboard</span></a></li>
    <li class="navigation-header"><span>Manajemen Pengaduan</span><i data-feather="more-horizontal"></i></li>
    <li class="nav-item {{ (request()->routeIs('departemen.pengaduan.*')) ? 'active' : '' }}"><a class="d-flex align-items-center" href="{{ route('departemen.pengaduan.index') }}"><i data-feather="package"></i><span class="menu-title text-truncate">Pengaduan</span> <span class="badge mr-1 ml-auto badge-light-danger badge-pill">{{$total_btl ?? ''}}</span></a></li>

@elseif (request()->is('pengawas*'))
    <li class="navigation-header"><span>Analytics</span><i data-feather="more-horizontal"></i></li>
    <li class="nav-item {{ (request()->routeIs('pengawas.dashboard.*')) ? 'active' : '' }}"><a class="d-flex align-items-center" href="{{route('pengawas.dashboard.index')}}"><i data-feather="home"></i><span class="menu-title text-truncate">Dashboard</span></a></li>
    <li class="navigation-header"><span>Manajemen Pengaduan</span><i data-feather="more-horizontal"></i></li>
    <li class="nav-item {{ (request()->routeIs('pengawas.pengaduan.*')) ? 'active' : '' }}"><a class="d-flex align-items-center" href="{{ route('pengawas.pengaduan.index') }}"><i data-feather="package"></i><span class="menu-title text-truncate">Pengaduan</span></a></li>

@endif