routes/web.php
<?php

use App\Models\ListRole;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require __DIR__.'/auth.php';

Route::get('', 'HomeController@index');
Route::get('/', 'HomeController@index');
Route::resource('/home', 'Front\HomeController');

//register
Route::get('/pendaftaran', 'Front\RegisterController@index');
Route::post('/pendaftaran/store', 'Front\RegisterController@store');
Route::resource('/cek-pengaduan', 'Front\CekPengaduanController');
Route::post('/search-pengaduan', 'Front\CekPengaduanController@searchPengaduan')->name('searchpengaduan');


Route::namespace('Admin')->name('admin.')->prefix('admin')->middleware('auth', 'role:admin')->group(function() {
    Route::namespace('Master')->name('master.')->prefix('master')->group(function() {
        Route::get('', 'HomeController@index');
        Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
        Route::resource('user', 'UserController');
        Route::get('data/user', 'UserController@data')->name('user.data');
        Route::resource('kategori-pengaduan', 'KategoriPengaduanController');
        Route::get('data/kategori-pengaduan', 'KategoriPengaduanController@data')->name('kategori-pengaduan.data');
        Route::resource('status-tindaklanjut', 'StatusTindaklanjutController');
        Route::get('data/status-tindaklanjut', 'StatusTindaklanjutController@data')->name('status-tindaklanjut.data');
        Route::resource('departemen', 'DepartemenController');
        Route::get('data/departemen', 'DepartemenController@data')->name('departemen.data');
        Route::resource('pengaduan', 'PengaduanController');
        Route::get('data/pengaduan', 'PengaduanController@data')->name('pengaduan.data');

        Route::resource('verifikasipengaduan', 'VerifikasiPengaduanController');
        Route::get('data/verifikasipengaduan', 'VerifikasiPengaduanController@data')->name('verifikasipengaduan.data');
    });
});

//pelapor
Route::namespace('Pelapor')->name('pelapor.')->prefix('pelapor')->middleware('auth', 'role:pelapor')->group(function() {
    Route::get('', 'HomeController@index');
    Route::resource('pengaduan', 'PengaduanController');
    Route::get('data/pengaduan', 'PengaduanController@data')->name('pengaduan.data');
    Route::get('pengaduan/getuserlogin', 'PengaduanController@getUserLogin');
    Route::get('/pengaduan/viewdetail/{id}', 'PengaduanController@viewDetail')->name('pengaduan.viewdetail'); 

    Route::resource('tindaklanjutpengaduan', 'TindakLanjutController');

    Route::resource('pengaduanditolak', 'PengaduanDitolakController');
    Route::resource('profile', 'ProfileController');
    Route::get('changepassword', 'ProfileController@viewChangePassword')->name('changepassword');
    Route::put('profile/changepassword/{id}', 'ProfileController@changePassword');
});

//departemen
Route::namespace('Departemen')->name('departemen.')->prefix('departemen')->middleware('auth', 'role:departemen')->group(function() {
    Route::get('', 'HomeController@index');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
    Route::resource('pengaduan', 'PengaduanController');
    Route::get('data/pengaduan', 'PengaduanController@data')->name('pengaduan.data');
    Route::get('/pengaduan/viewdetail/{id}', 'PengaduanController@viewDetail')->name('pengaduan.viewdetail'); 
    Route::post('/pengaduan/viewdetail/storetindaklanjut', 'PengaduanController@storetindaklanjut')->name('pengaduan.viewdetail.storetindaklanjut');
    Route::get('/pengaduan/viewdetail/edittindaklanjut/{id}', 'PengaduanController@edittindaklanjut')->name('pengaduan.viewdetail.edittindaklanjut');
    Route::put('/pengaduan/viewdetail/updatetindaklanjut/{id}', 'PengaduanController@updatetindaklanjut')->name('pengaduan.viewdetail.updatetindaklanjut');
    Route::put('/pengaduan/viewdetail/tutuppengaduan/{id}', 'PengaduanController@tutuppengaduan')->name('pengaduan.viewdetail.tutuppengaduan');
    Route::put('/pengaduan/viewdetail/bukapengaduan/{id}', 'PengaduanController@bukapengaduan')->name('pengaduan.viewdetail.bukapengaduan');
    Route::delete('/pengaduan/viewdetail/destroytindaklanjut/{id}', 'PengaduanController@destroytindaklanjut')->name('pengaduan.viewdetail.destroytindaklanjut');
});

//pengawas
Route::namespace('Pengawas')->name('pengawas.')->prefix('pengawas')->middleware('auth', 'role:pengawas')->group(function() {
    Route::get('', 'HomeController@index');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');
    Route::resource('pengaduan', 'PengaduanController');
    Route::get('data/pengaduan', 'PengaduanController@data')->name('pengaduan.data');
    Route::get('/pengaduan/viewdetail/{id}', 'PengaduanController@viewDetail')->name('pengaduan.viewdetail'); 
    Route::post('/pengaduan/viewdetail/storetindaklanjut', 'PengaduanController@storetindaklanjut')->name('pengaduan.viewdetail.storetindaklanjut');
    Route::get('/pengaduan/viewdetail/edittindaklanjut/{id}', 'PengaduanController@edittindaklanjut')->name('pengaduan.viewdetail.edittindaklanjut');
    Route::put('/pengaduan/viewdetail/updatetindaklanjut/{id}', 'PengaduanController@updatetindaklanjut')->name('pengaduan.viewdetail.updatetindaklanjut');
    Route::put('/pengaduan/viewdetail/tutuppengaduan/{id}', 'PengaduanController@tutuppengaduan')->name('pengaduan.viewdetail.tutuppengaduan');
    Route::put('/pengaduan/viewdetail/bukapengaduan/{id}', 'PengaduanController@bukapengaduan')->name('pengaduan.viewdetail.bukapengaduan');
    Route::delete('/pengaduan/viewdetail/destroytindaklanjut/{id}', 'PengaduanController@destroytindaklanjut')->name('pengaduan.viewdetail.destroytindaklanjut');
});

resources/views/pages/admin/departemen.blade.php
@extends('layout.layout')

@section('title', 'Departemen')

@section('css')
	<meta name="csrf-token" content="{{ csrf_token() }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/dataTables.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/buttons.bootstrap4.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/extensions/toastr.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/extensions/ext-component-toastr.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/extensions/sweetalert2.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/extensions/ext-component-sweet-alerts.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/pickers/flatpickr/flatpickr.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/forms/pickers/form-flat-pickr.min.css') }}">
@endsection

@section('content')
	{{-- BEGIN: Datatable Button --}}
	<section>
        {{-- BEGIN: Table --}}
        <x-datatable-button title="Data Departemen" id="tambah" buttonTitle='<i data-feather="plus"></i> Tambah'>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th data-priority="1">Departemen</th>
						<th>Status</th>
						<th data-priority="2">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    
                </tbody>
            </table>

            <form id="delete-form" action="#" method="POST" class="d-none">
                @csrf
                @method('DELETE')
            </form>
        </x-datatable-button>
        {{-- END: Table --}}
		
		{{-- BEGIN: Modal --}}
		<x-modal title="" type="normal" class="" id="modal">
            <form name="form" id="form" method="post">
                <div class="modal-body">
                    <x-form-group title="Departemen">
                        <input type="text" class="form-control" name="dept_nama" id="dept_nama" placeholder="Departemen" required/>
                    </x-form-group>
                    <x-form-group title="Status">
						<div>
							<input type="radio" id="dept_active_1" name="dept_active"  value="1" />
							<label for="radio_1">Aktif</label>
						</div>
				
						<div>
							<input type="radio" id="dept_active_0" name="dept_active"  value="0" />
							<label for="radio_2">Tidak Aktif</label>
						</div>
					</x-form-group>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary mr-1" id="button-tambah"><i data-feather="check"></i> Simpan</button>
                    <button type="submit" class="btn btn-primary mr-1" id="button-ubah"><i data-feather="edit-2"></i> Ubah</button>
                    <button type="reset" class="btn btn-outline-danger" id="button-batal" data-dismiss="modal"><i data-feather="x"></i> Batal</button>
                    <button type="button" class="btn btn-outline-danger" id="button-hapus"><i data-feather="trash"></i> Hapus</button>
                </div>
            </form>
		</x-modal>
		{{-- END: Modal --}}
	</section>
	{{-- END: Datatable Button --}}
@endsection

@section('js')
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
	<script src="{{ asset('app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js') }}"></script>
	<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.buttons.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/jszip.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/pdfmake.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/buttons.html5.min.js') }}"></script>
	<script src="{{ asset('app-assets/vendors/js/tables/datatable/buttons.print.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/extensions/toastr.min.js') }}"></script>
	<script src="{{ asset('app-assets/vendors/js/pickers/flatpickr/flatpickr.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/extensions/sweetalert2.all.min.js') }}"></script>
    <script src="{{ asset('app-assets/js/scripts/extensions/ext-component-sweet-alerts.js') }}"></script>

	{{-- Datatable --}}
	<script>
		var link = null;
	</script>
    {{-- Datatable --}}
	<script>
		var link = "{{ route('admin.master.departemen.data') }}";
		var column = [
			{data: 'dept_nama', name: 'dept_nama'},
            {data: 'dept_status', name: 'dept_status', orderable: false, searchable: false},
			{data: 'aksi', name: 'aksi', orderable: false, searchable: false}
		];
	</script>
	<script src="{{ asset('js/component/datatable-button.js') }}"></script>
	<script>
		// Modal
		$(document).ready(function() {
			$.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

			$('#tambah').on('click', function() {
				$('.modal-title').text('Tambah Departemen');
                $('#form').attr('action', "{{ url('/admin/master/departemen') }}");
				$('#button-tambah').attr('hidden', false);
				$('#button-batal').attr('hidden', false);
				$('#button-ubah').attr('hidden', true);
				$('#button-hapus').attr('hidden', true);
				
				$('#modal').modal('show');
			});

			$(document).on('click', '.ubah', function() {
				const id = $(this).attr('data-value');
				$('#button-hapus').attr('onClick', "hapus("+ $(this).attr('data-value') +")");
                $('#form').append('<input type="hidden" id="method" name="_method" value="PUT"/>');
				$.get( "{{ url('/admin/master/departemen') }}/"+ id, function( data ) {
					var d = JSON.parse(data);
					$('.modal-title').text('Ubah Departemen');
					$('#form').attr('action', "{{ url('/admin/master/departemen') }}/" + id);

					$('#dept_nama').val(d.dept_nama);
					$('#dept_active_'+ d.dept_active).prop('checked', true);
				});

				$('#button-tambah').attr('hidden', true);
				$('#button-batal').attr('hidden', true);
				$('#button-ubah').attr('hidden', false);
				$('#button-hapus').attr('hidden', false);


				$('#modal').modal('show');
			});

			$('#modal').on('hidden.bs.modal', function (e) {
				$('#form').attr('action', '');
                $('#method').remove();
				$('#dept_nama').val('');
                $('#dept_active_1').prop('checked', true);
				$('#dept_active_0').prop('checked', false);
			});

			// Tambah/Ubah Data
			$('#form').on('submit', function(e) {
				e.preventDefault();

				var formData = new FormData(this);

				$.ajax({
					url: $(this).attr('action'),
					type: "POST",
					data: formData,
					contentType: false,
					processData: false
				}).done(function(response){
					$('#modal').modal('hide');
					formExecuted(response);
				});
			});
		});

        function formExecuted(response) {
			var status = '';
			if (response.id == 1) {
				status = 'success';
				table.ajax.reload();
			} else {
				status = 'error';
			}
			toastr[status](response.keterangan, response.status, {
				closeButton: true,
				tapToDismiss: true
			});
		}

		// Hapus Data
		function hapus(id) {
			Swal.fire({
				title: 'Yakin ingin hapus?',
				icon: 'warning',
				showCancelButton: true,
				confirmButtonText: 'Ya',
				cancelButtonText: 'Tidak',
				customClass: {
					confirmButton: 'btn btn-primary',
					cancelButton: 'btn btn-outline-danger ml-1'
				},
				buttonsStyling: false
			}).then(function (result) {
				if (result.value) {
					var status = '';
					$.ajax({
						url: '{{ url("/admin/master/departemen")}}/'+ id,
						type: "POST",
						data: {
							_method: 'DELETE',
						},
					}).done(function(response){
						if (response.id == 1) {
							status = 'success';
							table.ajax.reload();
							$('#modal').modal('hide');
						} else {
							status = 'error';
						}
						toastr[status](response.keterangan, response.status, {
							closeButton: true,
							tapToDismiss: true
						});
					});
				}
			});
		}
	</script>
@endsection

resources/views/pages/admin/kategori_pengaduan.blade.php
@extends('layout.layout')

@section('title', 'Kategori Pengaduan')

@section('css')
	<meta name="csrf-token" content="{{ csrf_token() }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/dataTables.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/tables/datatable/buttons.bootstrap4.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/extensions/toastr.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/extensions/ext-component-toastr.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/extensions/sweetalert2.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/extensions/ext-component-sweet-alerts.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('app-assets/vendors/css/pickers/flatpickr/flatpickr.min.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('app-assets/css/plugins/forms/pickers/form-flat-pickr.min.css') }}">
@endsection

@section('content')
	{{-- BEGIN: Datatable Button --}}
	<section>
        {{-- BEGIN: Table --}}
        <x-datatable-button title="Data Kategori Pengaduan" id="tambah" buttonTitle='<i data-feather="plus"></i> Tambah'>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th data-priority="1">Kategori Pengaduan</th>
						<th>Status</th>
						<th data-priority="2">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    
                </tbody>
            </table>

            <form id="delete-form" action="#" method="POST" class="d-none">
                @csrf
                @method('DELETE')
            </form>
        </x-datatable-button>
        {{-- END: Table --}}
		
		{{-- BEGIN: Modal --}}
		<x-modal title="" type="normal" class="" id="modal">
            <form name="form" id="form" method="post">
                <div class="modal-body">
                    <x-form-group title="Kategori Pengaduan">
                        <input type="text" class="form-control" name="kp_nama" id="kp_nama" placeholder="Kategori Pengaduan" required/>
                    </x-form-group>
                    <x-form-group title="Status">
						<div>
							<input type="radio" id="kp_active_1" name="kp_active"  value="1" />
							<label for="radio_1">Aktif</label>
						</div>
				
						<div>
							<input type="radio" id="kp_active_0" name="kp_active"  value="0" />
							<label for="radio_2">Tidak Aktif</label>
						</div>
					</x-form-group>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary mr-1" id="button-tambah"><i data-feather="check"></i> Simpan</button>
                    <button type="submit" class="btn btn-primary mr-1" id="button-ubah"><i data-feather="edit-2"></i> Ubah</button>
                    <button type="reset" class="btn btn-outline-danger" id="button-batal" data-dismiss="modal"><i data-feather="x"></i> Batal</button>
                    <button type="button" class="btn btn-outline-danger" id="button-hapus"><i data-feather="trash"></i> Hapus</button>
                </div>
            </form>
		</x-modal>
		{{-- END: Modal --}}
	</section>
	{{-- END: Datatable Button --}}
@endsection

@section('js')
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js') }}"></script>
	<script src="{{ asset('app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js') }}"></script>
	<script src="{{ asset('app-assets/vendors/js/tables/datatable/datatables.buttons.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/jszip.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/pdfmake.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/tables/datatable/buttons.html5.min.js') }}"></script>
	<script src="{{ asset('app-assets/vendors/js/tables/datatable/buttons.print.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/extensions/toastr.min.js') }}"></script>
	<script src="{{ asset('app-assets/vendors/js/pickers/flatpickr/flatpickr.min.js') }}"></script>
    <script src="{{ asset('app-assets/vendors/js/extensions/sweetalert2.all.min.js') }}"></script>
    <script src="{{ asset('app-assets/js/scripts/extensions/ext-component-sweet-alerts.js') }}"></script>

	{{-- Datatable --}}
	<script>
		var link = null;
	</script>
    {{-- Datatable --}}
	<script>
		var link = "{{ route('admin.master.kategori-pengaduan.data') }}";
		var column = [
			{data: 'kp_nama', name: 'kp_nama'},
            {data: 'kp_status', name: 'kp_status', orderable: false, searchable: false},
			{data: 'aksi', name: 'aksi', orderable: false, searchable: false}
		];
	</script>
	<script src="{{ asset('js/component/datatable-button.js') }}"></script>
	<script>
		// Modal
		$(document).ready(function() {
			$.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

			$('#tambah').on('click', function() {
				$('.modal-title').text('Tambah Kategori Pengaduan');
                $('#form').attr('action', "{{ url('/admin/master/kategori-pengaduan') }}");
				$('#button-tambah').attr('hidden', false);
				$('#button-batal').attr('hidden', false);
				$('#button-ubah').attr('hidden', true);
				$('#button-hapus').attr('hidden', true);
				
				$('#modal').modal('show');
			});

			$(document).on('click', '.ubah', function() {
				const id = $(this).attr('data-value');
				$('#button-hapus').attr('onClick', "hapus("+ $(this).attr('data-value') +")");
                $('#form').append('<input type="hidden" id="method" name="_method" value="PUT"/>');
				$.get( "{{ url('/admin/master/kategori-pengaduan') }}/"+ id, function( data ) {
					var d = JSON.parse(data);
					$('.modal-title').text('Ubah Kategori Pengaduan');
					$('#form').attr('action', "{{ url('/admin/master/kategori-pengaduan') }}/" + id);

					$('#kp_nama').val(d.kp_nama);
					$('#kp_active_'+ d.kp_active).prop('checked', true);
				});

				$('#button-tambah').attr('hidden', true);
				$('#button-batal').attr('hidden', true);
				$('#button-ubah').attr('hidden', false);
				$('#button-hapus').attr('hidden', false);


				$('#modal').modal('show');
			});

			$('#modal').on('hidden.bs.modal', function (e) {
				$('#form').attr('action', '');
                $('#method').remove();
				$('#kp_nama').val('');
                $('#kp_active_1').prop('checked', true);
				$('#kp_active_0').prop('checked', false);
			});

			// Tambah/Ubah Data
			$('#form').on('submit', function(e) {
				e.preventDefault();

				var formData = new FormData(this);

				$.ajax({
					url: $(this).attr('action'),
					type: "POST",
					data: formData,
					contentType: false,
					processData: false
				}).done(function(response){
					$('#modal').modal('hide');
					formExecuted(response);
				});
			});
		});

        function formExecuted(response) {
			var status = '';
			if (response.id == 1) {
				status = 'success';
				table.ajax.reload();
			} else {
				status = 'error';
			}
			toastr[status](response.keterangan, response.status, {
				closeButton: true,
				tapToDismiss: true
			});
		}

		// Hapus Data
		function hapus(id) {
			Swal.fire({
				title: 'Yakin ingin hapus?',
				icon: 'warning',
				showCancelButton: true,
				confirmButtonText: 'Ya',
				cancelButtonText: 'Tidak',
				customClass: {
					confirmButton: 'btn btn-primary',
					cancelButton: 'btn btn-outline-danger ml-1'
				},
				buttonsStyling: false
			}).then(function (result) {
				if (result.value) {
					var status = '';
					$.ajax({
						url: '{{ url("/admin/master/kategori-pengaduan")}}/'+ id,
						type: "POST",
						data: {
							_method: 'DELETE',
						},
					}).done(function(response){
						if (response.id == 1) {
							status = 'success';
							table.ajax.reload();
							$('#modal').modal('hide');
						} else {
							status = 'error';
						}
						toastr[status](response.keterangan, response.status, {
							closeButton: true,
							tapToDismiss: true
						});
					});
				}
			});
		}
	</script>
@endsection